version: '2'

# should we add hostname to dockerfile

services:

  solr:
    image: lukecampbell/docker-ckan-solr
    container_name: solr

  postgis:
    image: mdillon/postgis:9.3
    container_name: postgis
    # Override these in a production environment
    env_file: env
    volumes:
      - /var/lib/docker-volumes/postgis:/var/lib/postgresql/data

  redis:
    image: redis:3.0.7-alpine
    container_name: redis

  ioos-catalog:
    build: .
    container_name: ioos-catalog
    env_file: env
    ports:
      - "80:80"

