version: '2'

# should we add hostname to dockerfile

services:

  solr:
    image: lukecampbell/docker-ckan-solr
    container_name: solr
    volumes:
      - solr_core_data:/opt/solr/example/solr

  postgis:
    image: mdillon/postgis:9.3
    container_name: postgis
    # Override these in a production environment
    env_file: env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:3.0.7-alpine
    container_name: redis

  ioos-catalog:
    image: ioos/ckanext-ioos-theme
    container_name: ioos-catalog
    env_file: env
    ports:
      - "80:80"

volumes:
  solr_core_data:
    external:
      name: solr_core_data

  pg_data:
    external:
      name: pg_data

